---
- hosts: yarn
  become: yes
  vars_files:
    - "{{ secrets_path }}"
  tasks:
    - name: Create group
      group: 
        name: hadoop 
        state: present
    - name: Create user
      user: 
        name: hduser 
        comment: "hduser" 
        group: hadoop 
        groups: sudo 
        shell: /bin/bash

- name: Install samza job server
  hosts: "yarn-master"
  become: yes
  vars_files:
    - "{{ secrets_path }}"
  roles:
    - java
    - yarn
    - samza-job-server

- name: Install java on all yarn slaves
  hosts: "yarn-slave"
  become: yes
  vars_files:
    - "{{ secrets_path }}"
  remote_user: hduser
  roles:
    - java
